version: '3.8'

# Development overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount source code for live reloading
      - ./src:/app/src:ro
      - ./scripts:/app/scripts:ro
      - ./init_database.py:/app/init_database.py:ro
      - ./database_schema.sql:/app/database_schema.sql:ro
    environment:
      # Enable development settings
      RELOAD: "true"
      DB_ECHO: "false"  # Set to "true" for SQL debugging
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"
    command: >
      sh -c "
        echo 'Starting in DEVELOPMENT mode with live reloading...'
        && uvicorn src.main:app --reload --host 0.0.0.0 --port 8000 --log-level info
      "
    
  # Optional: Enable detailed PostgreSQL logging for development
  postgres:
    command: >
      postgres 
      -c log_statement=all 
      -c log_destination=stderr 
      -c log_min_duration_statement=0
      -c log_line_prefix='%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
    environment:
      POSTGRES_DB: email_generator
      POSTGRES_USER: email_user  
      POSTGRES_PASSWORD: secure_email_password_123
      # Enable debug logging
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
